// <auto-generated />
using HotelSysteem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelSysteem.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20260120105727_FixHotelKamerBeddenHotelKamerVoorzieningenEntity")]
    partial class FixHotelKamerBeddenHotelKamerVoorzieningenEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelKamerBeddenHotelKamerVoorzieningen", b =>
                {
                    b.Property<int>("BeddenId")
                        .HasColumnType("int");

                    b.Property<int>("VoorzieningenId")
                        .HasColumnType("int");

                    b.HasKey("BeddenId", "VoorzieningenId");

                    b.HasIndex("VoorzieningenId");

                    b.ToTable("HotelKamerBeddenHotelKamerVoorzieningen", (string)null);
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerBed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bedden");
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerBedden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Aantal")
                        .HasColumnType("int");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.ToTable("Beddens");
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerVoorzieningen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Badkamers")
                        .HasColumnType("int");

                    b.Property<bool>("Balkon")
                        .HasColumnType("bit");

                    b.Property<int?>("KamerId")
                        .HasColumnType("int");

                    b.Property<int>("Oppervlakte")
                        .HasColumnType("int");

                    b.Property<int>("Slaapkamers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voorzieningens");
                });

            modelBuilder.Entity("HotelSysteem.Models.Hotelkamer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<int>("VoorzieningenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoorzieningenId")
                        .IsUnique();

                    b.ToTable("HotelKamers");
                });

            modelBuilder.Entity("HotelKamerBeddenHotelKamerVoorzieningen", b =>
                {
                    b.HasOne("HotelSysteem.Models.HotelKamerBedden", null)
                        .WithMany()
                        .HasForeignKey("BeddenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelSysteem.Models.HotelKamerVoorzieningen", null)
                        .WithMany()
                        .HasForeignKey("VoorzieningenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerBedden", b =>
                {
                    b.HasOne("HotelSysteem.Models.HotelKamerBed", "Bed")
                        .WithMany("Bedden")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");
                });

            modelBuilder.Entity("HotelSysteem.Models.Hotelkamer", b =>
                {
                    b.HasOne("HotelSysteem.Models.HotelKamerVoorzieningen", "Voorzieningen")
                        .WithOne("Kamer")
                        .HasForeignKey("HotelSysteem.Models.Hotelkamer", "VoorzieningenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voorzieningen");
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerBed", b =>
                {
                    b.Navigation("Bedden");
                });

            modelBuilder.Entity("HotelSysteem.Models.HotelKamerVoorzieningen", b =>
                {
                    b.Navigation("Kamer");
                });
#pragma warning restore 612, 618
        }
    }
}
